# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-01 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_structure', '0002_auto_20170630_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='parent_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
