# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-05 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_structure', '0003_auto_20170701_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='parent_name',
        ),
        migrations.AddField(
            model_name='company',
            name='parent_id',
            field=models.IntegerField(default=None),
        ),
    ]
