# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-05 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_structure', '0005_auto_20170705_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='parent_id',
        ),
    ]
