# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-05 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_structure', '0007_company_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_structure.Company'),
        ),
    ]
