# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-09 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_structure', '0014_company_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='total',
        ),
    ]
