# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-09 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_structure', '0016_company_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='total',
            field=models.IntegerField(),
        ),
    ]
